# nix
#+title: Home Manager Configuration
#+property: header-args:nix :tangle home.nix
#+auto_tangle: t

* Home Manager Configuration
This is my personal Home Manager configuration. It manages my user environment in NixOS.

** Basic Configuration
Basic setup for Home Manager including user details and state version.

#+begin_src nix
{ config, pkgs, lib, ... }:

let
  cursor = pkgs.callPackage ./packages/cursor.nix {};
in
{
  # Basic Home Manager Configuration
  home = {
    username = "martin";
    homeDirectory = "/home/martin";
    stateVersion = "25.05";
    
    sessionVariables = {
      EDITOR = "vim";
    };
#+end_src

** Package Management
Organized list of packages installed through Home Manager.

#+begin_src nix
    # System Packages
    packages = with pkgs; [
      # Development Tools
      thefuck
      ripgrep
      fd
      clang
      cmake
      ansible
      vagrant
      
      # System Tools
      btop
      tmux
      
      # Fonts
      (nerd-fonts.override {
        fonts = [
          "JetBrainsMono"
          "Iosevka"
        ];
      })
      
      # Applications
      dropbox
      slack
      discord
      google-chrome
      brave
      spotify
      bitwarden
      _1password-cli
      _1password-gui
      
      # Python Development
      (python3.withPackages (ps: with ps; [
        pip
        virtualenv
        poetry-core
      ]))
      
      # Virtualization
      virt-manager
      
      # Audio
      jamesdsp
      
      # Custom Packages
      cursor
    ];
  };

  # Allow Unfree Packages
  nixpkgs.config.allowUnfree = true;
#+end_src

** Shell Configuration
Configuration for ZSH and related shell tools.

#+begin_src nix
  # Shell Configuration
  programs = {
    # ZSH Configuration
    zsh = {
      enable = true;
      enableCompletion = true;
      
      plugins = [
        {
          name = "zsh-autosuggestions";
          src = pkgs.fetchFromGitHub {
            owner = "zsh-users";
            repo = "zsh-autosuggestions";
            rev = "v0.7.0";
            sha256 = "KLUYpUu4DHRumQZ3w59m9aTW6TBKMCXl2UcKi4uMd7w=";
          };
        }
        {
          name = "zsh-syntax-highlighting";
          src = pkgs.fetchFromGitHub {
            owner = "zsh-users";
            repo = "zsh-syntax-highlighting";
            rev = "0.7.1";
            sha256 = "gOG0NLlaJfotJfs+SUhGgLTNOnGLjoqnUp54V9aFJg8=";
          };
        }
      ];

      oh-my-zsh = {
        enable = true;
        plugins = [ "git" "history" "tmux" ];
        theme = "robbyrussell";
      };

      initExtra = ''
        if [ -f "${config.home.homeDirectory}/.dotfiles/zsh/.zshrc" ]; then
          echo "Loading custom zshrc..."
          source "${config.home.homeDirectory}/.dotfiles/zsh/.zshrc"
        fi
      '';
    };
#+end_src

** Terminal and Development Tools
Configuration for terminal emulators and development tools.

#+begin_src nix
    # Terminal Emulators
    alacritty.enable = true;
    kitty.enable = true;

    # Development Tools
    emacs = {
      enable = true;
      package = pkgs.emacs29;
    };

    # CLI Tools
    eza.enable = true;
    bat.enable = true;
    starship.enable = true;
#+end_src

** Git Configuration
Git configuration including work-specific settings.

#+begin_src nix
    # Git Configuration
    git = {
      enable = true;
      userName = "bloodstiller";
      userEmail = "bloodstiller@bloodstiller.com";
      
      extraConfig = {
        init.defaultBranch = "main";
        pull.rebase = false;
        core.editor = "vim";
        credential.helper = "store";
      };

      includes = [{
        condition = "gitdir:~/.config/work/";
        contents = {
          user = {
            email = "mbarker@babblevoice.com";
            name = "Martin Barker";
          };
        };
      }];
    };
#+end_src

** Tmux Configuration
Tmux configuration with plugin management.

#+begin_src nix
    # Tmux Configuration
    tmux = {
      enable = true;
      plugins = with pkgs.tmuxPlugins; [
        sensible
      ];
      
      extraConfig = ''
        source ${config.home.homeDirectory}/.dotfiles/tmux/.tmux.conf
        
        set -g @plugin 'tmux-plugins/tpm'
        set -g @plugin 'tmux-plugins/tmux-sensible'
        
        run '~/.tmux/plugins/tpm/tpm'
      '';
    };
  };
#+end_src

** Window Manager Configuration
Hyprland window manager configuration.

#+begin_src nix
  # Window Manager Configuration
  wayland.windowManager.hyprland = {
    enable = true;
    systemd = {
      enable = true;
      variables = ["--all"];
    };
    xwayland.enable = true;
    
    settings = {
      monitor = ",preferred,auto,1";
      general = {
        gaps_in = 5;
        gaps_out = 10;
        border_size = 2;
      };
    };
  };
#+end_src

** Theme Configuration
System-wide theme and cursor configuration.

#+begin_src nix
  # Theme Configuration
  home.pointerCursor = {
    gtk.enable = true;
    package = pkgs.bibata-cursors;
    name = "Bibata-Modern-Classic";
    size = 16;
  };

  gtk = {
    enable = true;
    theme = {
      package = pkgs.flat-remix-gtk;
      name = "Flat-Remix-GTK-Grey-Darkest";
    };
    iconTheme = {
      package = pkgs.adwaita-icon-theme;
      name = "Adwaita";
    };
    font = {
      name = "Sans";
      size = 11;
    };
  };
#+end_src

** Dotfile Management
Management of various configuration files and directories.

#+begin_src nix
  # Dotfile Management
  home.file = {
    # TPM Installation
    ".tmux/plugins/tpm".source = pkgs.fetchFromGitHub {
      owner = "tmux-plugins";
      repo = "tpm";
      rev = "99469c4a9b1ccf77fade25842dc7bafbc8ce9946";
      sha256 = "hW8mfwB8F9ZkTQ72WQp/1fy8KL1IIYMZBtZYIwZdMQc=";
    };

    # Config Files
    ".config/doom" = {
      source = ~/.dotfiles/doom;
      recursive = true;
    };
    
    ".config/alacritty" = {
      source = ~/.dotfiles/alacritty;
      recursive = true;
    };

    # Shell Config
    ".zshrc".source = ~/.dotfiles/zsh/.zshrc;
    ".config/starship.toml".source = ~/.dotfiles/starship/starship.toml;

    # Window Manager Config
    ".config/hypr" = {
      source = ~/.dotfiles/hypr;
      recursive = true;
    };

    # Application Config
    ".config/dunst" = {
      source = ~/.dotfiles/dunst;
      recursive = true;
    };
    
    ".config/wofi" = {
      source = ~/.dotfiles/wofi;
      recursive = true;
    };
    
    ".config/waybar" = {
      source = ~/.dotfiles/waybar;
      recursive = true;
    };

    # Scripts
    ".config/scripts" = {
      source = ~/.dotfiles/scripts;
      executable = true;
    };

    # ZSH Config Directory
    ".config/zsh" = {
      source = ~/.dotfiles/zsh;
      recursive = true;
    };
  };
#+end_src

** Service Configuration
System service configuration including Dropbox.

#+begin_src nix
  # Service Configuration
  systemd.user.services.dropbox = {
    Unit = {
      Description = "Dropbox service";
    };
    Install = {
      WantedBy = [ "default.target" ];
    };
    Service = {
      ExecStart = "${pkgs.dropbox}/bin/dropbox";
      Restart = "on-failure";
    };
  };

  # Enable Services
  services.dunst.enable = true;
  programs = {
    wofi.enable = true;
    waybar.enable = true;
    home-manager.enable = true;
  };
}
#+end_src
